---
# Ingress system namespace (sobaseki node)
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
  labels:
    app.kubernetes.io/name: ingress-system
    node-affinity: sobaseki
    skies/tier: ingress

---
# Database system namespace (alikara node)
apiVersion: v1
kind: Namespace
metadata:
  name: database-system
  labels:
    app.kubernetes.io/name: database-system
    node-affinity: alikara
    skies/tier: infra

---
# Monitoring system namespace (alikara node)
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-system
  labels:
    app.kubernetes.io/name: monitoring-system
    node-affinity: alikara
    skies/tier: infra

---
# Analytics system namespace (sobaseki node)
apiVersion: v1
kind: Namespace
metadata:
  name: analytics-system
  labels:
    app.kubernetes.io/name: analytics-system
    node-affinity: sobaseki
    skies/tier: app

---
# Backend application namespace (sobaseki node)
apiVersion: v1
kind: Namespace
metadata:
  name: app-backend
  labels:
    app.kubernetes.io/name: app-backend
    node-affinity: sobaseki
    skies/tier: app

---
# Frontend application namespace (sobaseki node)
apiVersion: v1
kind: Namespace
metadata:
  name: app-frontend
  labels:
    app.kubernetes.io/name: app-frontend
    node-affinity: sobaseki
    skies/tier: app
